# numpy

* 数値計算や配列計算をサポートする拡張モジュール

## ndarray(numpy配列)

* asarrayメソッドで取得する

In [6]:
import numpy as np
num_list = [1,2,3,4,5]
print(num_list)

nd_ary = np.asarray(num_list)
print(type(nd_ary))

print(nd_ary)

for i in nd_ary:
    print(i)

[1, 2, 3, 4, 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]
1
2
3
4
5


In [9]:
# ループもできる
import numpy as np
num_list = [[1,2,3], [4,5,6], [7,8,9]]
nd_ary = np.asarray(num_list)

print(nd_ary)

for i in nd_ary:
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[4 5 6]
[7 8 9]


## ndarrayをリストに変換

* tolistメソッドを利用
    * リスト ↔ numpy配列 の変換はよく使う

In [12]:
import numpy as np
num_list = [[1,2,3], [4,5,6], [7,8,9]]
nd_ary = np.asarray(num_list)

# リストに変換
to_list = nd_ary.tolist()
print(nd_ary)
print(to_list)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


## 型を指定して配列を取得

* uint(符号なし整数)やcomplexなども指定できる

In [25]:
import numpy as np
num_list = [[1,2,3], [4,5,6], [7,8,9]]

print(np.asarray(num_list, dtype = np.int64))
print(np.asarray(num_list, dtype = np.float64))
print(np.asarray(num_list, dtype = np.float64).tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]


## 型を変更

* astypeメソッドを利用する
* 破壊的メソッドではなく変更したものが返される

In [31]:
import numpy as np
num_list = [[1,2,3], [4,5,6], [7,8,9]]

nd_ary = np.asarray(num_list)
print(nd_ary)
print(nd_ary.astype(np.float64))

# nd_aryの型は変更されていない
print(nd_ary)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 配列初期化

* empty
    * 初期化しない
        * 値は都度異なる
        * 初期化しなので生成は高速
        * 初期化済みの場合は何もしない
* zeros
    * 0.0で初期化
* ones
    * 1.0で初期化
* arange
    * 連番で初期化
* full
    * 任意の値で初期化
* identity
    * 行列同じの正方形で初期化
* diag
    * 対角要素の取得

In [60]:
import numpy as np
print(np.empty(8))
print(np.empty([4,3]))
print(np.zeros(5))
print(np.zeros([2,3]))
print(np.ones(6))
print(np.ones([3,3]))
print(np.arange(2,5,0.5))
print(np.full((2,2), 7))
print(np.identity(3))

num_list = [[1,2,3], [4,5,6], [7,8,9]]
print(np.asarray(num_list))
print(np.diag(num_list))

[6.95332146e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
[[6.95332149e-310 6.92298238e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]
[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[2.  2.5 3.  3.5 4.  4.5]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


## 型を指定して初期化

* dtypeで指定

In [62]:
import numpy as np
print(np.empty(9, dtype=np.bool))
print(np.zeros([2,3], dtype=np.int64))
print(np.ones([3,3], dtype=np.int64))

[ True False False False  True False False False  True]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


## ndarrayの構造確認

* ndim
    * 次元数
* size
    * 要素数
* shape
    * 次元毎の要素数
* nbytes
    * 全体のサイズ(バイト数)
* dtype
    * 型

In [73]:
import numpy as np
nd_ary = np.zeros((3,2,4), dtype=np.int64)
print(nd_ary)

print(nd_ary.ndim)
print(nd_ary.size)
print(nd_ary.shape)
print(nd_ary.nbytes)
print(nd_ary.dtype)

[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]
3
24
(3, 2, 4)
192
int64


## 行列の取り出し

In [80]:
import numpy as np
num_list = [[1,2,3], [4,5,6], [7,8,9]]

nd_ary = np.asarray(num_list)
print(nd_ary)

### 2行目取り出し
print(nd_ary[1,:])

### 2列目取り出し
print(nd_ary[:,1])

### 2行2列目の要素を取り出し
print(nd_ary[1,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[2 5 8]
5
