# Pillow

* Python の画像処理ライブラリ
* PIL(Python Imaging Library : Python2.7まで)のforkプロジェクト
    * 3系対応
* 参考
    * [Python 3.5 対応画像処理ライブラリ Pillow (PIL) の使い方](https://librabuch.jp/blog/2013/05/python_pillow_pil/)

## 画像を新規で作成する

* テキストを画像に出力する
    * 新規の画像は `Image.new` でcanvasを作成する
    * canvas
        * 画像を貼り付ける部分
    * `ImageDraw` で画像オブジェクトを処理する
    * `Image.save` で保存する
    * `draw.text((10, 10), 'hogehoge', font=font, fill='#000')`
        * fill : 16進数でカラーコードを指定
            * `#000` は黒
        * font : フォントの種類とサイズを指定
        * `(10,10)` : 画像の座標の始点

In [1]:
### テスト(テキストを画像で出力)
from PIL import Image, ImageDraw, ImageFont

# 画像オブジェクトを作成。サイズと背景色を指定する。背景色はRBGの各々をtupleにして与える。
text_canvas = Image.new('RGB', (80, 40), (255, 255, 255))
draw = ImageDraw.Draw(text_canvas)

# フォントの種類とサイズを指定
#font = ImageFont.truetype('/Library/Fonts/ipag.ttf', 15)
font = ImageFont.truetype('/root/.fonts/ipag.ttf', 15)

# テキストを書き込み。引数は順に、書き込み座標（tuple）、テキスト、テキストのフォント、テキストのカラー
draw.text((10, 10), 'hogehoge', font=font, fill='#000')

# 保存
text_canvas.save('img/text_img.jpg', 'JPEG', quality=100, optimize=True)

テスト画像の表示

既存

<img src="img/text_img.jpg" alt="テスト画像の表示" title="テスト画像の表示" align="left" />  

<br clear="left">

## 既存の画像を開く

* 既存の画像を開いてリサイズして別名のファイルに保存
    * 既存の画像は `Image.open` で開く

In [2]:
from PIL import Image

# 既存ファイルを readモードで読み込み
img = Image.open('img/text_img.jpg', 'r')

# リサイズ。サイズは幅と高さをtupleで指定
resize_img = img.resize((160, 80))

# リサイズ後の画像を保存
resize_img.save('img/text_img_resize.jpg', 'JPEG', quality=100, optimize=True)

リサイズ後

<img src="img/text_img_resize.jpg" alt="テスト画像の表示_resize" title="テスト画像の表示_resize" align="left" />  

<br clear="left">


## ロボ団の単語帳作成

* [ChatGPT](https://chatgpt.com/c/682421eb-d5ec-800b-8843-0a6e60f5816e)

以下の画像を点線で切り取って単語帳にする

<img src="img/robodan01_parts_omote.jpg" alt="ロボ団表" title="ロボ団表" width="50%" align="left" />  

<br clear="left">

In [16]:
## 単語帳作成
from PIL import Image
import os

# 入力ファイル名（画像と同じフォルダに置いてください）
#card_name = "robodan03_parts_omote"
#card_name = "robodan03_parts_ura"
#card_name = "robodan04_hole_omote"
card_name = "robodan04_hole_ura"
input_path = f"img/robodan/{card_name}.jpg"

# 出力フォルダ名
output_folder = "img/robodan/output_cards"
os.makedirs(output_folder, exist_ok=True)

# 行数と列数（5行×4列）
rows = 5
cols = 4

# 画像を開く
image = Image.open(input_path)
img_width, img_height = image.size

# カード1枚のサイズを計算
card_width = img_width // cols
card_height = img_height // rows

# 分割して保存
for row in range(rows):
    for col in range(cols):
        left = col * card_width
        upper = row * card_height
        right = left + card_width
        lower = upper + card_height
        card = image.crop((left, upper, right, lower))
        card.save(f"{output_folder}/{card_name}_card_{row+1}_{col+1}.jpg")

print(f"{rows * cols} 枚のカードを '{output_folder}' に保存しました。")

20 枚のカードを 'img/robodan/output_cards' に保存しました。


## 単語帳アプリの作成

In [1]:
# Tkinterテスト
import tkinter as tk

In [2]:
root = tk.Tk()
root.mainloop()

In [6]:
%%bash
ls /home/ftakao2007/finance/repositories/python/jupyter_notebook/Python/img/robodan/output_cards/work/okset01

card_01_back.jpg
card_01_front.jpg
card_02_back.jpg
card_02_front.jpg
card_03_back.jpg
card_03_front.jpg
card_04_back.jpg
card_04_front.jpg
card_05_back.jpg
card_05_front.jpg
card_06_back.jpg
card_06_front.jpg
card_07_back.jpg
card_07_front.jpg
card_08_back.jpg
card_08_front.jpg
card_09_back.jpg
card_09_front.jpg
card_10_back.jpg
card_10_front.jpg
card_11_back.jpg
card_11_front.jpg
card_12_back.jpg
card_12_front.jpg
card_13_back.jpg
card_13_front.jpg
card_14_back.jpg
card_14_front.jpg
card_15_back.jpg
card_15_front.jpg
card_16_back.jpg
card_16_front.jpg
card_17_back.jpg
card_17_front.jpg
card_18_back.jpg
card_18_front.jpg
card_19_back.jpg
card_19_front.jpg
card_20_back.jpg
card_20_front.jpg
rename_omote.lst
rename_omote.sh
rename_ura.lst
rename_ura.sh


In [15]:
import os
import tkinter as tk
from PIL import Image, ImageTk

# フォルダパス（画像が入っている）
image_folder = "img/robodan/output_cards/work/okset01"

# 画像ファイル一覧を取得（jpg限定、ソートしておく）
image_files = sorted([f for f in os.listdir(image_folder) if f.endswith(".jpg")])

# カードインデックス
index = 0

# ウィンドウ作成
root = tk.Tk()
root.title("単語カードビューア")

# キャンバスと画像表示
canvas = tk.Label(root)
canvas.pack()

def show_image():
    global index
    path = os.path.join(image_folder, image_files[index])
    img = Image.open(path)
    img = img.resize((400, 300), Image.Resampling.LANCZOS)  # 修正済み
    img_tk = ImageTk.PhotoImage(img)
    canvas.image = img_tk  # ← ここが重要！canvasに属性として保持
    canvas.config(image=img_tk)
    root.title(f"{image_files[index]} ({index+1}/{len(image_files)})")

def next_card():
    global index
    if index < len(image_files) - 1:
        index += 1
        show_image()

def prev_card():
    global index
    if index > 0:
        index -= 1
        show_image()

# ナビゲーションボタン
btn_prev = tk.Button(root, text="← 前へ", command=prev_card)
btn_prev.pack(side="left", padx=10, pady=10)

btn_next = tk.Button(root, text="次へ →", command=next_card)
btn_next.pack(side="right", padx=10, pady=10)

# 最初の画像は mainloop 後に表示させる
#show_image()
root.after(100, show_image)

# アプリ起動
root.mainloop()

## NumPyとPILの変換

* Python Imaging LibraryのImageクラスのデータをNumPyのarrayとして扱う
    * Numpyの関数を使って直接pixel値を書き換える
* 参考
    * [NumPyのarrayとPILの変換](http://d.hatena.ne.jp/white_wheels/20100322/p1)

### PILのImageオブジェクトを配列に変換

* asarray関数
    * NumPyの関数
    * PILのImageオブジェクトを配列に変換する

In [4]:
import numpy as np
from PIL import Image

img = Image.open('img/text_img.jpg', 'r')
imgArray = np.asarray(img)
print(imgArray.shape)
print('-----------------------')
print(imgArray)
print('-----------------------')
print(imgArray[0][1])

try:
    imgArray[0][1][0] = 100
except ValueError:
    print('配列の要素を変更するにはwriteableフラグをTrueにする必要があります。')

imgArray.flags.writeable = True
imgArray[0][1] = 100
print(imgArray[0][1])

(40, 80, 3)
-----------------------
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
-----------------------
[255 255 255]
配列の要素を変更するにはwriteableフラグをTrueにする必要があります。


ValueError: cannot set WRITEABLE flag to True of this array

### NumPyのarrayからPILへの変換

* fromarrayメソッド
    * PILのメソッド
    * 配列の各値を1byte整数型(0～255)として画像のpixel値に変換する

In [5]:
pilImg = Image.fromarray(np.uint8(imgArray))
print(pilImg)

# 画像を保存
pilImg.save('img/text_img_numpy.jpg', 'JPEG', quality=100, optimize=True)

# ローカルで実行している場合はshowコマンドで画像ファイルを作成せずに表示できる
#pilImg.show()

<PIL.Image.Image image mode=RGB size=80x40 at 0x7F83C36BCB50>


リサイズ後

<img src="img/text_img_numpy.jpg" alt="numpy画像の保存" title="numpy画像の保存" align="left" />  

<br clear="left">

※ 画像の左上についてるゴマみたいな点が配列の値を直接書き換えることによってできた