# Pillow

* Python の画像処理ライブラリ
* PIL(Python Imaging Library : Python2.7まで)のforkプロジェクト
    * 3系対応
* 参考
    * [Python 3.5 対応画像処理ライブラリ Pillow (PIL) の使い方](https://librabuch.jp/blog/2013/05/python_pillow_pil/)

## 画像を新規で作成する

* テキストを画像に出力する
    * 新規の画像は `Image.new` でcanvasを作成する
    * canvas
        * 画像を貼り付ける部分
    * `ImageDraw` で画像オブジェクトを処理する
    * `Image.save` で保存する
    * `draw.text((10, 10), 'hogehoge', font=font, fill='#000')`
        * fill : 16進数でカラーコードを指定
            * `#000` は黒
        * font : フォントの種類とサイズを指定
        * `(10,10)` : 画像の座標の始点

In [6]:
### テスト(テキストを画像で出力)
from PIL import Image, ImageDraw, ImageFont

# 画像オブジェクトを作成。サイズと背景色を指定する。背景色はRBGの各々をtupleにして与える。
text_canvas = Image.new('RGB', (80, 40), (255, 255, 255))
draw = ImageDraw.Draw(text_canvas)

# フォントの種類とサイズを指定
#font = ImageFont.truetype('/Library/Fonts/ipag.ttf', 15)
font = ImageFont.truetype('/root/.fonts/ipag.ttf', 15)

# テキストを書き込み。引数は順に、書き込み座標（tuple）、テキスト、テキストのフォント、テキストのカラー
draw.text((10, 10), 'hogehoge', font=font, fill='#000')

# 保存
text_canvas.save('img/text_img.jpg', 'JPEG', quality=100, optimize=True)

テスト画像の表示

既存

<img src="img/text_img.jpg" alt="テスト画像の表示" title="テスト画像の表示" align="left" />  

<br clear="left">

## 既存の画像を開く

* 既存の画像を開いてリサイズして別名のファイルに保存
    * 既存の画像は `Image.open` で開く

In [10]:
from PIL import Image

# 既存ファイルを readモードで読み込み
img = Image.open('img/text_img.jpg', 'r')

# リサイズ。サイズは幅と高さをtupleで指定
resize_img = img.resize((160, 80))

# リサイズ後の画像を保存
resize_img.save('img/text_img_resize.jpg', 'JPEG', quality=100, optimize=True)

リサイズ後

<img src="img/text_img_resize.jpg" alt="テスト画像の表示_resize" title="テスト画像の表示_resize" align="left" />  

<br clear="left">


## NumPyとPILの変換

* Python Imaging LibraryのImageクラスのデータをNumPyのarrayとして扱う
    * Numpyの関数を使って直接pixel値を書き換える
* 参考
    * [NumPyのarrayとPILの変換](http://d.hatena.ne.jp/white_wheels/20100322/p1)

### PILのImageオブジェクトを配列に変換

* asarray関数
    * NumPyの関数
    * PILのImageオブジェクトを配列に変換する

In [29]:
import numpy as np
from PIL import Image

img = Image.open('img/text_img.jpg', 'r')
imgArray = np.asarray(img)
print(imgArray.shape)
print('-----------------------')
print(imgArray)
print('-----------------------')
print(imgArray[0][1])

try:
    imgArray[0][1][0] = 100
except ValueError:
    print('配列の要素を変更するにはwriteableフラグをTrueにする必要があります。')

imgArray.flags.writeable = True
imgArray[0][1] = 100
print(imgArray[0][1])

(40, 80, 3)
-----------------------
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ..., 
 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
-----------------------
[255 255 255]
配列の要素を変更するにはwriteableフラグをTrueにする必要があります。
[100 100 100]


### NumPyのarrayからPILへの変換

* fromarrayメソッド
    * PILのメソッド
    * 配列の各値を1byte整数型(0～255)として画像のpixel値に変換する

In [31]:
pilImg = Image.fromarray(np.uint8(imgArray))
print(pilImg)

# 画像を保存
pilImg.save('img/text_img_numpy.jpg', 'JPEG', quality=100, optimize=True)

# ローカルで実行している場合はshowコマンドで画像ファイルを作成せずに表示できる
#pilImg.show()

<PIL.Image.Image image mode=RGB size=80x40 at 0x7F56393D14A8>


リサイズ後

<img src="img/text_img_numpy.jpg" alt="numpy画像の保存" title="numpy画像の保存" align="left" />  

<br clear="left">

※ 画像の左上についてるゴマみたいな点が配列の値を直接書き換えることによってできた